### ISSUE TITLE
Warning with EventEmitter

### ISSUE THREAD

**Issue by jtrueblood-anaqua** [Badisi/ngx-safe-subscribe#3]
Hello Badisi,  

Great code, thanks for sharing!  

I am having an issue when using a setter for a Component's property.  
```javascript
_myElement: myElement;

@Output()
myElementChange = new EventEmitter<myyElement>();

@Input()
get myElement() {
	return this._myElement;
}

set myElement(newVal: myElement) {    
	if (this._myElement === newVal) { return; }
	this._myElement = newVal;
	this.cd.markForCheck();
	this.myElementChange.emit(this._myElement);
}
```

When calling `this.myElementChange.emit(this._myElement);`,  the console shows the "should implement OnDestory..." warning.  

Any thoughts on how to handle safeSubscribe in this situation?

**Comment by jtrueblood-anaqua** [comment]
I was able to track down the error. I was neglecting to pass `this` into safeSubscribe for a dynamically added component.

**Comment by Badisi** [comment]
Closing the issue as you managed to solved it by yourself.
Thanks for the kind words !
